[workspace]
members = ["blockset", "blockset-lib"]
resolver = "2"

[workspace.package]
version = "0.3.6"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Sergey Shandar"]
repository = "https://github.com/datablockset/blockset"

[workspace.dependencies]
io-trait = "0.4.0"
io-impl = "0.4.0"
io-test = "0.4.0"
wasm-bindgen-test = "0.3.37"
