[package]
name = "blockset"
description = "Data Block Set"
version = "0.3.3"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Sergey Shandar"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.149"

[dev-dependencies]
wasm-bindgen-test = "0.3.37"
