[package]
name = "blockset"
description = "Data Block Set"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io-trait.workspace = true
io-impl.workspace = true

[dev-dependencies]
io-test.workspace = true
wasm-bindgen-test.workspace = true
