name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo clippy -- -D warnings

  run-wasmtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@wasmtime
      - run: rustup target add wasm32-wasi
      - run: cargo build --target wasm32-wasi --release
      - run: wasmtime ./target/wasm32-wasi/release/blockset.wasm validate c02hb4h8s6v05pxpnhcyxdebewfbwbrg6sp3k46hsh6qc

  test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@wasm-pack
      - run: wasm-pack test --node --release ./blockset-lib

  test:
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners
        os: [windows-latest, ubuntu-latest, macos-14]
        type: ['', '--release']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: cargo test ${{ matrix.type }}

  coverage:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-tarpaulin
    - run: cargo c
    - uses: actions/upload-artifact@v3
      with:
        path: tarpaulin-report.html
      if: always()
